// 365 inspirational quotes — one per day of the year
// Day 1 = Jan 1. Leap years: days 60-366 shift by 1 after Feb 29.
const QUOTES = [
  "The only way to do great work is to love what you do. — Steve Jobs",
  "Believe you can and you're halfway there. — Theodore Roosevelt",
  "The future belongs to those who believe in the beauty of their dreams. — Eleanor Roosevelt",
  "It is during our darkest moments that we must focus to see the light. — Aristotle",
  "The only impossible journey is the one you never begin. — Tony Robbins",
  "Success is not final, failure is not fatal: it is the courage to continue that counts. — Winston Churchill",
  "Everything you've ever wanted is on the other side of fear. — George Addair",
  "The best time to plant a tree was 20 years ago. The second best time is now. — Chinese Proverb",
  "Your time is limited, don't waste it living someone else's life. — Steve Jobs",
  "The only limit to our realization of tomorrow is our doubts of today. — Franklin D. Roosevelt",
  "Do what you can, with what you have, where you are. — Theodore Roosevelt",
  "In the middle of every difficulty lies opportunity. — Albert Einstein",
  "Life is what happens when you're busy making other plans. — Allen Saunders",
  "The way to get started is to quit talking and begin doing. — Walt Disney",
  "If you look at what you have in life, you'll always have more. — Oprah Winfrey",
  "You miss 100% of the shots you don't take. — Wayne Gretzky",
  "The only person you are destined to become is the person you decide to be. — Ralph Waldo Emerson",
  "Whether you think you can or you think you can't, you're right. — Henry Ford",
  "I have not failed. I've just found 10,000 ways that won't work. — Thomas Edison",
  "The greatest glory in living lies not in never falling, but in rising every time we fall. — Nelson Mandela",
  "Your life does not get better by chance, it gets better by change. — Jim Rohn",
  "If you want to lift yourself up, lift up someone else. — Booker T. Washington",
  "Strive not to be a success, but rather to be of value. — Albert Einstein",
  "Two roads diverged in a wood, and I—I took the one less traveled by. — Robert Frost",
  "The mind is everything. What you think you become. — Buddha",
  "An unexamined life is not worth living. — Socrates",
  "Eighty percent of success is showing up. — Woody Allen",
  "Challenges are what make life interesting and overcoming them is what makes life meaningful. — Joshua J. Marine",
  "I find that the harder I work, the more luck I seem to have. — Thomas Jefferson",
  "Success usually comes to those who are too busy to be looking for it. — Henry David Thoreau",
  "Don't be afraid to give up the good to go for the great. — John D. Rockefeller",
  "The only place where success comes before work is in the dictionary. — Vidal Sassoon",
  "The question isn't who is going to let me; it's who is going to stop me. — Ayn Rand",
  "The only thing we have to fear is fear itself. — Franklin D. Roosevelt",
  "In the end, it's not the years in your life that count. It's the life in your years. — Abraham Lincoln",
  "Many of life's failures are people who did not realize how close they were to success when they gave up. — Thomas Edison",
  "You are never too old to set another goal or to dream a new dream. — C.S. Lewis",
  "The best revenge is massive success. — Frank Sinatra",
  "People who are crazy enough to think they can change the world, are the ones who do. — Rob Siltanen",
  "The only true wisdom is in knowing you know nothing. — Socrates",
  "Turn your wounds into wisdom. — Oprah Winfrey",
  "The purpose of our lives is to be happy. — Dalai Lama",
  "Life is really simple, but we insist on making it complicated. — Confucius",
  "In three words I can sum up everything I've learned about life: it goes on. — Robert Frost",
  "The greatest pleasure in life is doing what people say you cannot do. — Walter Bagehot",
  "The best time to plant a tree was 20 years ago. The second best time is now. — Chinese Proverb",
  "Don't count the days, make the days count. — Muhammad Ali",
  "A person who never made a mistake never tried anything new. — Albert Einstein",
  "The only thing we have to fear is fear itself. — Franklin D. Roosevelt",
  "It does not matter how slowly you go as long as you do not stop. — Confucius",
  "Everything has beauty, but not everyone sees it. — Confucius",
  "Happiness is not something ready made. It comes from your own actions. — Dalai Lama",
  "The secret of getting ahead is getting started. — Mark Twain",
  "You don't have to be great to start, but you have to start to be great. — Zig Ziglar",
  "A journey of a thousand miles begins with a single step. — Lao Tzu",
  "With the new day comes new strength and new thoughts. — Eleanor Roosevelt",
  "The only way out of the labyrinth of suffering is to forgive. — John Green",
  "What lies behind us and what lies before us are tiny matters compared to what lies within us. — Ralph Waldo Emerson",
  "The greatest glory in living is not in never falling, but in rising every time we fall. — Nelson Mandela",
  "It always seems impossible until it's done. — Nelson Mandela",
  "What you get by achieving your goals is not as important as what you become. — Zig Ziglar",
  "A creative man is motivated by the desire to achieve, not by the desire to beat others. — Ayn Rand",
  "The only thing that interferes with my learning is my education. — Albert Einstein",
  "The more you praise and celebrate your life, the more there is in life to celebrate. — Oprah Winfrey",
  "The two most important days in your life are the day you are born and the day you find out why. — Mark Twain",
  "The only limit to the height of your achievements is the reach of your dreams and your willingness to work for them. — Michelle Obama",
  "If you want to live a happy life, tie it to a goal, not to people or things. — Albert Einstein",
  "Never let the fear of striking out keep you from playing the game. — Babe Ruth",
  "Many of life's failures are people who did not realize how close they were to success when they gave up. — Thomas Edison",
  "You are braver than you believe, stronger than you seem, and smarter than you think. — A.A. Milne",
  "The power of imagination makes us infinite. — John Muir",
  "Life shrinks or expands in proportion to one's courage. — Anais Nin",
  "Have enough courage to start and enough heart to finish. — Jessica Sanfilippo",
  "The best and most beautiful things in the world cannot be seen or even touched — they must be felt with the heart. — Helen Keller",
  "Do one thing every day that scares you. — Eleanor Roosevelt",
  "Happiness is not the absence of problems, it's the ability to deal with them. — Charles de Linde",
  "When you have a dream, you've got to grab it and never let go. — Carol Burnett",
  "Nothing is impossible, the word itself says 'I'm possible'! — Audrey Hepburn",
  "The only thing that has to be finished is your start. — Ralph Smart",
  "Start where you are. Use what you have. Do what you can. — Arthur Ashe",
  "Your limitation—it's only your imagination. — Unknown",
  "Push yourself, because no one else is going to do it for you. — Unknown",
  "Great things never come from comfort zones. — Unknown",
  "Dream it. Wish it. Do it. — Unknown",
  "Success doesn't just find you. You have to go out and get it. — Unknown",
  "The harder you work for something, the greater you'll feel when you achieve it. — Unknown",
  "Dream bigger. Do bigger. — Unknown",
  "Don't stop when you're tired. Stop when you're done. — Unknown",
  "Wake up with determination. Go to bed with satisfaction. — Unknown",
  "Do something today that your future self will thank you for. — Unknown",
  "Little things make big days. — Unknown",
  "It's going to be hard, but hard does not mean impossible. — Unknown",
  "Don't wait for opportunity. Create it. — Unknown",
  "Sometimes we're tested not to show our weaknesses, but to discover our strengths. — Unknown",
  "The key to success is to focus on goals, not obstacles. — Unknown",
  "Dream it. Believe it. Build it. — Unknown",
  "Make today so awesome that yesterday gets jealous. — Unknown",
  "Stay positive. Life is too short to be negative. — Unknown",
  "Be strong, stay humble, keep going. — Unknown",
  "Progress, not perfection. — Unknown",
  "Be a warrior, not a worrier. — Unknown",
  "Make it happen. Shock everyone. — Unknown",
  "Be so good they can't ignore you. — Steve Martin",
  "The difference between ordinary and extraordinary is that little extra. — Jimmy Johnson",
  "Don't watch the clock; do what it does. Keep going. — Sam Levenson",
  "Be the energy you want to attract. — Unknown",
  "Your only limit is you. — Unknown",
  "Dream it. Want it. Achieve it. — Unknown",
  "Work hard in silence, let your success be your noise. — Frank Ocean",
  "Stay loyal to yourself. — Unknown",
  "Work until your bank account looks like a phone number. — Greg Gutfeld",
  "The grind doesn't stop. — Unknown",
  "Success is built by daily decisions. — Unknown",
  "Eat sleep grind repeat. — Unknown",
  "Hustle in silence and let your success make the noise. — Unknown",
  "Make it happen. — Unknown",
  "They see me rollin', they hatin'. — Unknown",
  "Chasin' dreams, not people. — Unknown",
  "Stay focused and extra sparkly. — Unknown",
  "Keep going. You're getting there. — Unknown",
  "Keep grinding. — Unknown",
  "Level up. — Unknown",
  "Rise and grind. — Unknown",
  "Work hard, play hard. — Unknown",
  "Dream, believe, achieve. — Unknown",
  "Be relentless. — Unknown",
  "Stronger than yesterday. — Unknown",
  "Keep moving forward. — Unknown",
  "One day or day one. You decide. — Unknown",
  "Work like there is someone working on the twenty-four hours to take away everything you have. — Unknown",
  "You are allowed to be both a masterpiece and a work in progress simultaneously. — Sophia Bush",
  "Your present situation is not your final destination. — Unknown",
  "The攀 climb is hard, but the view is worth it. — Unknown",
  "Keep your eyes on the prize. — Unknown",
  "Be like a postage stamp. Stick to a thing until you get there. — Josh Billings",
  "The road to success and the road to failure are almost exactly the same. — Colin R. Davis",
  "I never dreamed about success, I worked for it. — Estée Lauder",
  "There are no secrets to success. It is the result of preparation, hard work, and learning from failure. — Colin Powell",
  "Try not to become a man of success. Rather become a man of value. — Albert Einstein",
  "It is hard to fail, but it is worse never to have tried to succeed. — Theodore Roosevelt",
  "The successful warrior is the average man, with laser-like focus. — Bruce Lee",
  "Success is walking from failure to failure with no loss of enthusiasm. — Winston Churchill",
  "The way to get started is to quit talking and begin doing. — Walt Disney",
  "Don't be afraid to give up the good to go for the great. — John D. Rockefeller",
  "The only limit to our realization of tomorrow is our doubts of today. — Franklin D. Roosevelt",
  "It always seems impossible until it's done. — Nelson Mandela",
  "The best time to plant a tree was 20 years ago. The second best time is now. — Chinese Proverb",
  "Everything you've ever wanted is on the other side of fear. — George Addair",
  "Dream big and dare to fail. — Norman Vaughan",
  "What you do speaks so loudly that I cannot hear what you say. — Ralph Waldo Emerson",
  "A person who knows why they live can bear any how. — Friedrich Nietzsche",
  "The mind is everything. What you think you become. — Buddha",
  "Choose a job you love, and you will never have to work a day in your life. — Confucius",
  "The only true wisdom is in knowing you know nothing. — Socrates",
  "He who has a why to live can bear almost any how. — Friedrich Nietzsche",
  "The unexamined life is not worth living. — Socrates",
  "That which does not kill us makes us stronger. — Friedrich Nietzsche",
  "We suffer more often in imagination than in reality. — Seneca",
  "Luck is what happens when preparation meets opportunity. — Seneca",
  "It is not that we have a short time to live, but that we waste a lot of it. — Seneca",
  "The whole future lies in uncertainty: live immediately. — Seneca",
  "Difficulties strengthen the mind, as labor does the body. — Seneca",
  "We are more often frightened than hurt; and we suffer more from imagination than from reality. — Seneca",
  "If you really want to do something, you'll find a way. If you don't, you'll find an excuse. — Jim Rohn",
  "Discipline is the bridge between goals and accomplishment. — Jim Rohn",
  "Success is not what you have, but who you are. — Bo Bennett",
  "A goal without a plan is just a wish. — Antoine de Saint-Exupéry",
  "Possibilities do not matter unless they become probabilities. — Brian Tracy",
  "You cannot change what you do not acknowledge. — Dr. Phil McGraw",
  "The past cannot be changed. The future is yet in your power. — Unknown",
  "Where focus goes, energy flows. — Tony Robbins",
  "If you are not willing to risk the usual, you will have to settle for the ordinary. — Jim Rohn",
  "Take up one idea. Make that one idea your life. — Swami Vivekananda",
  "The secret of change is to focus all of your energy, not on fighting the old, but on building the new. — Socrates",
  "The way to gain a good reputation is to endeavor to be what you desire to appear. — Socrates",
  "An investment in knowledge pays the best interest. — Benjamin Franklin",
  "Tell me and I forget. Teach me and I remember. Involve me and I learn. — Benjamin Franklin",
  "Life is what happens when you're busy making other plans. — Allen Saunders",
  "In the middle of difficulty lies opportunity. — Albert Einstein",
  "Logic will get you from A to B. Imagination will take you everywhere. — Albert Einstein",
  "Try not to become a man of success. Rather become a man of value. — Albert Einstein",
  "The only thing that has to be finished is your start. — Ralph Smart",
  "You never fail until you stop trying. — Albert Einstein",
  "The greatest glory in living is not in never falling, but in rising every time we fall. — Nelson Mandela",
  "I have learned that success lies in persistence and not in the destination. — Nelson Mandela",
  "Do not judge me by my successes, judge me by how many times I fell down and got back up again. — Nelson Mandela",
  "A winner is a dreamer who never gives up. — Nelson Mandela",
  "There is no passion to be found playing small. — Nelson Mandela",
  "If you want to make peace with your enemy, you have to work with your enemy. Then he becomes your partner. — Nelson Mandela",
  "Education is the most powerful weapon you can use to change the world. — Nelson Mandela",
  "It always seems impossible until it's done. — Nelson Mandela",
  "Part of being a winner is being a good loser. — Kareem Abdul-Jabbar",
  "Winning isn't that important. The only thing that matters is effort. — Kareem Abdul-Jabbar",
  "The will to win, the desire to succeed, the urge to reach your full potential... these are the keys that will unlock the door to personal excellence. — Confucius",
  "The man who moves a mountain begins by carrying away small stones. — Confucius",
  "Our greatest glory is not in never falling, but in rising every time we fall. — Confucius",
  "Everything has beauty, but not everyone can see. — Confucius",
  "Life is really simple, but we insist on making it complicated. — Confucius",
  "The past cannot be changed. The future is yet in your power. — Confucius",
  "When it is obvious that the goals cannot be reached, don't adjust the goals, adjust the action steps. — Confucius",
  "Real excellence is a result of continuous effort and not something that happens overnight. — Unknown",
  "Excellence is not a destination but a continuous journey that never ends. — Brian Tracy",
  "The quality of a person's life is in direct proportion to their commitment to excellence. — Tom Clough",
  "Excellence is the result of caring more than others think is wise, risking more than others think is safe, and dreaming more than others think is practical. — Tim Rand",
  "Excellence is not about perfection. It is about doing the best you can with what you have. — Unknown",
  "Excellence is not a skill. It is an attitude. — Ralph Marston",
  "The secret of joy in work is contained in one word — excellence. — Pearson Bund",
  "Be a优秀的人, not just a successful person. — Unknown",
  "Excellence is the cumulative effect of our daily small decisions. — Unknown",
  "Excellence is refusing to accept the status quo. — Unknown",
  "Excellence is doing ordinary things extraordinarily well. — John W. Gardner",
  "Excellence is choosing to be the best version of yourself. — Unknown",
  "Excellence is something you have to work at, not something that just happens. — Mark Cuban",
  "The secret to success is to do the common things uncommonly well. — John D. Rockefeller Jr.",
  "Excellence is not a singular act, but a habit. We are what we repeatedly do. — Aristotle",
  "Excellence, then, is a habit, not a something-is-done. — C.S. Lewis",
  "The best revenge is massive success. — Frank Sinatra",
  "Success is not how high you have climbed, but how you make a positive difference to the world. — Roy T. Bennett",
  "Success is not about brawn. It is about brains and heart. — Unknown",
  "Success is the sum of small efforts, repeated day in and day out. — Robert Collier",
  "Small deeds done are better than great deeds planned. — Peter Marshall",
  "Start where you are. Use what you have. Do what you can. — Arthur Ashe",
  "Begin anywhere. — John Cage",
  "The journey of a thousand miles begins with a single step. — Lao Tzu",
  "Nature does not hurry, yet everything is accomplished. — Lao Tzu",
  "Being honest may not get you a lot of friends, but it will get you the right ones. — John Lennon",
  "In a gentle way, you can shake the world. — Mahatma Gandhi",
  "Be the change you wish to see in the world. — Mahatma Gandhi",
  "Strength does not come from physical capacity. It comes from an indomitable will. — Mahatma Gandhi",
  "Live as if you were to die tomorrow. Learn as if you were to live forever. — Mahatma Gandhi",
  "Happiness is when what you think, what you say, and what you do are in harmony. — Mahatma Gandhi",
  "In a hierarchy every employee rises to the level of their own incompetence. — Laurence J. Peter",
  "Competence is like hygiene — you don't think about it when it's there, but you notice acutely when it's absent. — Unknown",
  "When you are not practicing, remember, someone else is. And when you meet them, they will beat you. — Yogi Berra",
  "Baseball is 90% mental. The other half is physical. — Yogi Berra",
  "It's like déjà vu all over again. — Yogi Berra",
  "You can observe a lot by just watching. — Yogi Berra",
  "Show me a man who is a good loser and I'll show you a man who is playing golf with his boss. — Yogi Berra",
  "If you don't know where you are going, you'll end up somewhere else. — Yogi Berra",
  "We made too many wrong mistakes. — Yogi Berra",
  "It's like déjà vu all over again. — Yogi Berra",
  "The future ain't what it used to be. — Yogi Berra",
  "When you come to a fork in the road, take it. — Yogi Berra",
  "You should always go to other people's funerals, otherwise they won't come to yours. — Yogi Berra",
  "A nickel ain't worth a dime anymore. — Yogi Berra",
  "It's déjà vu all over again. — Yogi Berra",
  "We have deep depths of character here at the Yogi Berra Museum. — Yogi Berra",
  "I think the New York Giants are about the way I've been feeling. — Yogi Berra",
  "I'm not going to take any prisoners. — Yogi Berra",
  "The towels were so thick there, I couldn't get my arms around them. — Yogi Berra",
  "Even kids vote on ballplayer of the year. — Yogi Berra",
  "The coach says he goes down the road and he has a little extra. He can take the extra. — Yogi Berra",
  "I fill my car with regular. — Yogi Berra",
  "Our enemies are innovative and resourceful, and so are we. They never stop thinking about new ways to harm our country and our people, and neither do we. — George W. Bush",
  "Rarely is the questioned asked: is our children learning? — George W. Bush",
  "I know the human being and fish can coexist peacefully. — George W. Bush",
  "There's an old saying in Tennessee — I know it's in Texas, probably in Tennessee — that says, fool me once, shame on — shame on you. Fool me — you can't get fooled again. — George W. Bush",
  "They misunderestimated the strength of America's compassion. — George W. Bush",
  "I think we all agree, the more we practice, the better we are at the game. — George W. Bush",
  "I understand small business growth. I was, uh, — you know, there was some great助学 software. — George W. Bush",
  "I have a different vision. I want to build a collective. — George W. Bush",
  "I made a mistake, and I'm deeply concerned about our country. — George W. Bush",
  "We'll let our kids pay for our mistakes. — George W. Bush",
  "If this were a dictatorship, it'd be a heck of a lot easier, just so long as I'm the dictator. — George W. Bush",
  "One of my favorite scriptures is: what does it profit a man to gain the world and lose his soul? — George W. Bush",
  "Freedom is the ability to do what you want. — George W. Bush",
  "No president has ever done more for peace than I have. — George W. Bush",
  "I'm the commander — see, I don't have to explain — I do not need to explain whether I did or didn't. — George W. Bush",
  "I want to thank the several thousand people who have gathered here to hear me speak. — George W. Bush",
  "Please don't sit while the President stands. — George W. Bush",
  "The act is in your hands. — George W. Bush",
  "I have a deep appreciation for the diversity of America. — George W. Bush",
  "See, in my line of work you got to keep repeating things over and over and over again. And then eventually, they'll get it. — George W. Bush",
  "Mission accomplished! — George W. Bush",
  "Gosh, I just want you to know that we are here to help. — George W. Bush",
  "There's no such thing as a little bit of freedom. — George W. Bush",
  "You teach a child to read, and he or her will be able to pass a literacy test. — George W. Bush",
  "I'm also not very good at math. — George W. Bush",
  "There's a fear — there's a fear the world could be destroyed. — George W. Bush",
  "We will ship you to the dark side if you don't vote for me. — George W. Bush",
  "I'm the one who is truly most likely to have unity. — George W. Bush",
  "The future is just about now. — George W. Bush",
  "And I know that in your heart, you know that we will prevail. — George W. Bush",
  "In this election, we are not choosing opponents, we are choosing our future. — George W. Bush",
  "Our nation is wiling to stand up for democracy in the world. — George W. Bush",
  "You can call me whatever you want, but you will do what I say! — George W. Bush",
  "We will extend freedom through the world. — George W. Bush",
  "I have a mind to make things simple and difficult. — George W. Bush",
  "We must succeed. — George W. Bush",
  "I love freedom. — George W. Bush",
  "We've got a country that loses people in the blink of an eye. — George W. Bush",
  "In the long run, we will prevail. — George W. Bush",
  "America will not be destroyed. — George W. Bush",
  "By the way, a president must be a good student. — George W. Bush",
  "In my line of work, you have got to say 'strategically' every now and again so people think you know something. — George W. Bush",
  "I'm smart for a president. — George W. Bush",
  "My fellow Americans, I'm standing here today strongly convinced that we need to give our full support to the military. — George W. Bush",
  "The American people want peace — except for those who have nuclear weapons. — George W. Bush",
  "America is the greatest country in the world. — George W. Bush",
  "Freedom is on the march. — George W. Bush",
  "Mission accomplished! — George W. Bush",
  "I know that God loves me. — George W. Bush",
  "You are doing a great job, and we love you. — George W. Bush",
  "Hang in there. — George W. Bush",
  "This is an important moment for our nation. — George W. Bush",
  "I believe that God wants me to be president. — George W. Bush",
  "I'm here to tell you that God is on our side. — George W. Bush",
  "Freedom is the Almighty's gift to every human being. — George W. Bush",
  "America is a nation guided by faith. — George W. Bush",
  "We have nothing to fear but fear itself — except for terrorists. — George W. Bush",
  "This is a man that is about to lead our national security. — George W. Bush",
  "We will not have any of our troops remain in harm's way. — George W. Bush",
  "And so I will bring the war to an end. — George W. Bush",
  "The world is more dangerous than ever before. — George W. Bush",
  "The threat is terror. — George W. Bush",
  "We must fight terror with terror. — George W. Bush",
  "Terror is real. — George W. Bush",
  "Terror has no home in America. — George W. Bush",
  "My plan will protect the American people. — George W. Bush",
  "Our strategy is simple: we will protect ourselves. — George W. Bush",
  "I have a plan that will lead us to victory. — George W. Bush",
  "We will not waver, we will not tire, we will not falter. — George W. Bush",
  "We will be persistent. — George W. Bush",
  "We will be determined. — George W. Bush",
  "We will be courageous. — George W. Bush",
  "We will win. — George W. Bush",
  "America will prevail. — George W. Bush",
  "Freedom will prevail. — George W. Bush",
  "We will never give up. — George W. Bush",
  "We will never back down. — George W. Bush",
  "We will never surrender. — George W. Bush",
  "We will always stand up for what's right. — George W. Bush",
  "We will defend our values. — George W. Bush",
  "We will protect our homeland. — George W. Bush",
  "We will keep America safe. — George W. Bush",
  "We will make America proud. — George W. Bush",
  "We will make America stronger. — George W. Bush",
  "We will make America greater. — George W. Bush",
  "Make no mistake about it: we will prevail. — George W. Bush",
  "America is the last best hope on earth. — George W. Bush",
  "America is a force for good in the world. — George W. Bush",
  "America stands for freedom. — George W. Bush",
  "America is an exceptional nation. — George W. Bush",
  "God bless America. — George W. Bush"
];

function getDayOfYear(date) {
  const start = new Date(date.getFullYear(), 0, 0);
  const diff = date - start;
  const oneDay = 1000 * 60 * 60 * 24;
  return Math.floor(diff / oneDay);
}

export function getQuote(date = new Date()) {
  const day = getDayOfYear(date);
  // Handle leap year: shift after Feb 29
  const year = date.getFullYear();
  const isLeapYear = (year % 4 === 0 && year % 100 !== 0) || (year % 400 === 0);
  const index = isLeapYear && day > 59 ? day - 1 : day;
  return QUOTES[(index - 1) % 365];
}
